name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsqlite3-dev lld openjdk-17-jdk shared-mime-info autoconf automake libtool pkg-config zlib1g-dev libffi-dev libssl-dev libltdl-dev expect
          pip install --upgrade pip
          pip install buildozer cython==0.29.36

      - name: Pre-Accept Licenses
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          expect -c "
            set timeout -1
            spawn buildozer android licenses
            expect {
              \"*Accept?*\" { send \"y\r\"; exp_continue }
              eof
            }
          " || true

      - name: Build Android APK
        run: buildozer android debug
        env:
          P4A_RELEASE_KEY: ""

      - name: Upload Finished APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SatChannelEditor-Pro-APK
          path: bin/*.apk
